#!/bin/bash

process_list=(
"F5.app"
)

# Kill processes if any are given as argument.
for process in "${process_list[@]}"; do
  # Terminate gracefully
  osascript -e "quit app \"$process\""
  sleep 1
  # Get process id and kill process. Exclude "PKInstallSandbox" to not accidentally terminate other installations.
  for process_id in $(ps -ax | grep "$process" | grep -v "PKInstallSandbox" | grep -v "grep" | awk '{print $1}'); do
    echo "INFO: Process '$process' with PID '$process_id' is running, will now kill forcefully!"
    kill -9 "$process_id"
  done
done
